### ISSUE TITLE
Add `link-search` line?

### ISSUE THREAD

**Issue by jonathanstrong** [termoshtt/link_cuda_kernel#1]
On my system, the build.rs file needed the following line to compile:

```rust
println!("cargo:rustc-link-search=native=/usr/local/cuda/lib64");
```

Still learning rust ffi and this took ages to figure out. Thought it might be useful to add to the build.rs (perhaps even commented out).

**Comment by termoshtt** [comment]
This is distribution specific issue. You may use ubuntu or ubuntu-based distribution which use `/usr/loca/cuda/` as CUDA installation directory. It may be `/opt/cuda` on other distribution, e.g. [ArchLinux](https://wiki.archlinux.org/index.php/GPGPU#CUDA). It should be resolved by `LIBRARY_PATH`  and `LD_LIBRARY_PATH` environment value since Rust uses `ld` for linking (or [lld](https://github.com/rust-lang/rust/issues/39915) in future), however, the comment for it will be useful.

**Comment by jonathanstrong** [comment]
fwiw I checked (many times) that `/usr/local/cuda/lib64` was in my `LD_LIBRARY_PATH` but that did not matter. Using ubuntu 16.04.

**Comment by termoshtt** [comment]
The README is updated. Does this make sense?

**Comment by jonathanstrong** [comment]
much improved!

**Comment by termoshtt** [comment]
Thank :)
